trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Set up Java 17'

- script: |
    javac HelloJenkins.java
  displayName: 'Compile Java Program'

- script: |
    java HelloJenkins
  displayName: 'Run Java Program'
